### ISSUE TITLE
Link to here from BananaBread?

### ISSUE THREAD

**Issue by kripken** [cfoust/sour#1]
Really awesome stuff here!

What do you think about linking to here from the BananaBread repo? Now and then people ask there about whether there is any news in this space.

**Comment by cfoust** [comment]
Sure! I will clean up the README for this repo and then make a pull request in BananaBread when I get the chance. My plan is to attempt to update the engine to the latest Sauerbraten revision, which may make this a bit more appealing :tada:

**Comment by kripken** [comment]
Sounds great!

**Comment by cfoust** [comment]
I'm not sure if just adding the PR notifies you. FYI @kripken

**Comment by kripken** [comment]
PR merged (sorry for the delay), closing.
