### ISSUE TITLE
Healthboost, Armor & Quad appears too early

### ISSUE THREAD

**Issue by kwadroke** [cfoust/sour#10]
When joining the Sour server on Sourga.me; the Healthboost, Green & Yellow Armor, and Quad Damage items appear on the screen before they are actually spawned. You can not pick them up until they spawn in game. Then will then disappear like they are supposed to when picked up.

Tested on Sourga.me using Chromium on Linux.

**Comment by cfoust** [comment]
Does this happen on every server or just the one accessible through "play" on the main menu?

**Comment by kwadroke** [comment]
That's a good question. I only jumped into a couple of other servers for a few minutes to see if it worked. I primarily played through the "play" menu option. I want to say I saw the same thing on other servers, but, I wasn't in them long enough to notice/remember. Will test against some others.

**Comment by kwadroke** [comment]
Currently not getting any servers listed in the Server Browser via sourga.me, so I can't test other servers at the moment. Will try again later.
If the list still doesn't update later, I'll open another issue for that.

**Comment by kwadroke** [comment]
Please note that the item issue only appears after the start of a map. If you join a map after the items have already spawned, there is not an issue.

**Comment by cfoust** [comment]
Ah, that makes sense. Right now there's a bug in the relay server which is causing it to crash after a while. Thank you for reporting!

**Comment by kwadroke** [comment]
Issue also exists on Firefox. 

Might be an issue with Health pickups as well. Researching.

**Comment by cfoust** [comment]
I did end up fixing this. Servers now load game maps to place entities properly, including spawns and flags. Web clients also delay initializing entities until after the map loads.
