### ISSUE TITLE
I'ts not opnening

### ISSUE THREAD

**Issue by ZEGERMANMAN** [cfoust/sour#18]
Before your latest update all i would see is the text that it show as soon as you click on the link but it would not load i even waited about an hour and no change and with your latest update it is now just a white screen is there anyway you can revert/fix the game?

**Comment by cfoust** [comment]
Taking a look! Sorry about that!

**Comment by cfoust** [comment]
looks like it's back :)

**Comment by ZEGERMANMAN** [comment]
Thank you.
