### ISSUE TITLE
Heroku?

### ISSUE THREAD

**Issue by eris-webserv** [cfoust/sour#2]
Would it be possible to host this on heroku? I wanna add it to my site because, well, Bananabread is awesome so this is too. 
If so, can you add the Deploy to Heroku button or just put a tutorial here?

**Comment by nuggetofwisdom** [comment]
Yes!

**Comment by nuggetofwisdom** [comment]
> Would it be possible to host this on heroku? I wanna add it to my site because, well, Bananabread is awesome so this is too. If so, can you add the Deploy to Heroku button or just put a tutorial here?

Do you already have the completed bb.html build? If so can you link it because I can't compile this for the life of me
@erisfiregamer1

**Comment by eris-webserv** [comment]
I can't compile it! Mainly because no PC D:

**Comment by nuggetofwisdom** [comment]
@Erisfiregamer1 Ahhhh I have a pc and everything I could possibly need to compile it except for the knowledge needed.

**Comment by cfoust** [comment]
Hmm, I've never used Heroku but I'm sure this could be packaged for it. Sour can be deployed with a Docker image, but it's not just a static set of assets like BananaBread was because it has a game server. Also, the assets can be rather large (I host all of them on S3 + CloudFront.) What issues were y'all having with compiling? I think that I should probably create a deployment guide.

**Comment by eris-webserv** [comment]
@cfoust Honestly, if you could provide the docker image, I could host a client on Heroku. Which, I would, because I want to test this.

**Comment by cfoust** [comment]
Haha I've been meaning to just generate and distribute a Docker image for this. It's possible (the build is working again, by the way) but allowing users to choose what maps go into the image is not set up yet.

**Comment by cfoust** [comment]
Hey there! I now provide a Docker image. See [this comment](https://github.com/cfoust/sour/issues/5#issuecomment-1059786066).
