### ISSUE TITLE
Sour not loading on Gitpod

### ISSUE THREAD

**Issue by catfoolyou** [cfoust/sour#52]
When I try to deploy the repo on Gitpod, the game is stuck on "Loading Index Data (0/2)"

I have no idea how to fix this. Maybe it has something to do with the "Deprecated. Please use the Project Settings to configure prebuilds." error?

**Comment by cfoust** [comment]
interesting, huh, lemme take a look

**Comment by cfoust** [comment]
Gitpod is notoriously unstable and I haven't worked on Sour in a while, so it may have broken somehow

**Comment by catfoolyou** [comment]
I don't think there is any way to deploy it locally, as I have no admin access on this PC, and can't install Emscripten or NodeJS. Might try to do it when I get home.

**Comment by catfoolyou** [comment]
Also is there a way to deploy the original BananaBread? bb.html isnt in the repo anymore and I have no idea how to make it work either...

**Comment by cfoust** [comment]
I've thought about ways to make this much better recently, such as packaging up Sour as a single Go executable that would include the web client and the backend, which is totally possible. BananaBread is long gone and almost everything it included has been replaced. If you're looking to do something specific with Sour beyond hacking on it, I'd be happy to give you some pointers!

**Comment by cfoust** [comment]
So I tried this out and it is working, it's just that generating assets takes a while, after which you can refresh and it works. But honestly this is pretty awful; there's no way to know that's what's going on when you click the Gitpod link. So I'll revisit this and make it better soon. It used to wait until everything had been built before even displaying the page, but that broke at some point

**Comment by catfoolyou** [comment]
Ah, alright. Would it be possible to build it into a js/html game on linux so that it would run by itself? Without things like NodeJS, Emscripten, Docker, etc as it is not available where I am planning to deploy it.

**Comment by cfoust** [comment]
Yup! That's the goal! I will think about how and when I can prioritize this for you!

**Comment by catfoolyou** [comment]
Thanks. I'll try getting BananaBread to work in the meantime for offline bot deathmatch.

**Comment by cfoust** [comment]
You can now deploy Sour locally; instead of using Docker, it is now just a single executable available for macOS and Linux. Let me know if you have any trouble using it!

**Comment by catfoolyou** [comment]
Thanks, will definitely try this. Sorry for not replying earlier, was kinda busy with stuff

**Comment by cfoust** [comment]
All good! Take it easy.
